### ISSUE TITLE
Indexing a Surv-object creates numeric

### ISSUE THREAD

**Issue by gugl58** [HenrikBengtsson/doFuture#24]
"doFuture" seems to break Surv-objects of the package "survival" if only parts are taken. 
Is this really a bug and how could it be fixed?

MWE:
  
	library(survival)
	library(doFuture)
	testfun <- function(survival_vector){
		return.list <- list()
		for(i in 10:12){
			return.list <- c(return.list, list(survival_vector[1:i]))
		}
		return(return.list)
	}
	testfun_parallel <- function(survival_vector){
		return.list <- foreach(i=10:12) %dopar%{
			survival_vector[1:i]
		}
		return(return.list)
	}
	
	
	
	survvec <- with(lung, Surv(time, status))
	
	
	registerDoFuture()
	plan(multiprocess, workers = 4L)
	a <- testfun(survvec)
	b <- testfun_parallel(survvec)
	
	# Here comes the problem: 
	identical(a[[1]], b[[1]]) # FALSE
	class(a[[1]]) # "Surv"
	class(b[[1]]) # "numeric"

**Comment by HenrikBengtsson** [comment]
Hi, thanks for reporting.

Although not immediately obvious, this one falls under Section 'Missing packages (false negatives)' in the ['A Future for R: Common Issues with Solutions'](https://cran.r-project.org/web/packages/future/vignettes/future-2-issues.html) vignette of the [future](https://cran.r-project.org/package=future) package.

It's a corner case where the future framework simply fails to identify that the 'survival' package needs to be loaded on the R worker.  The solution is to manually guide doFuture to loaded 'survival' by specifying argument `.packages` of `foreach()`, i.e.

```r
foreach(i = 10:12, .packages = "survival") %dopar% {
   ...
}
```


# Details on the problem

I'm posting a longer explanation here in case other search the web on similar problems and end up here.  A minimal illustration of the problem using plain futures:

```r
library("future")
plan(multisession, workers = 2L)

library("survival")
x <- with(lung, Surv(time, status))

y_truth <- x[1]
str(y_truth)
# Surv [1, 1:2] 306 
# - attr(*, "dimnames")=List of 2
#  ..$ : NULL
#  ..$ : chr [1:2] "time" "status"
# - attr(*, "type")= chr "right"
stopifnot(inherits(y_truth, "Surv"))

y %<-% x[1]
str(y)
# num 306
stopifnot(inherits(y, "Surv"))
Error: inherits(y, "Surv") is not TRUE
```

The reason for the "bug" is that `x[1]` does not end up subsetting using `survival:::``[.Surv()``` because the 'survival' package is not loaded on the background R worker.  This causes the subsetting to be done using R's built-in `[` function.  By forcing 'survival' to be loaded, the proper subsetting function will be available and used.

```r
y %<-% { x[1] } %packages% "survival"
```


Note that the 'survival' package is indeed automatically loaded if one call one of it's (other non-`[`) functions inside the future expression, which is often case in most code.  For instance, the following works without having to explicitly specify the package:

```r
library("future")
plan(multisession, workers = 2L)

library("survival")
x <- with(lung, Surv(time, status))

fit_truth <- survfit(x[1:10] ~ sex[1:10], data = lung)

fit %<-% survfit(x[1:10] ~ sex[1:10], data = lung)

stopifnot(identical(fit, fit_truth))
```

In the doFuture example,

```r
library("doFuture")
registerDoFuture()
plan(multisession, workers = 2L)

library("survival")
survvec <- with(lung, Surv(time, status))

res <- foreach(i = 10:12, .packages = "survival") %dopar% {
  survfit(survvec[1:i] ~ sex[1:i], data = lung)
}
```

Hope this helps and clarifies what's going on.

PS. I'll probably update the vignette to also mention the `[` issue using 'survival' as an example (in addition to 'data.table').

**Comment by gugl58** [comment]
Sorry for bothering and thank you for your immediate answer! You created a great package!

**Comment by HenrikBengtsson** [comment]
No problem at all. This kind of feedback helps identify issues and possible fixes
