### ISSUE TITLE
how to use plan() in package

### ISSUE THREAD

**Issue by jkurle** [HenrikBengtsson/doFuture#49]
First of all thank you so much for providing this package, @HenrikBengtsson!

I am currently writing my own package and want to use the doFuture (future), foreach, and doRNG packages in a foreach loop. I have read a few of the issues on this topic (#375, HenrikBengtsson/future#274, HenrikBengtsson/future#327, https://github.com/HenrikBengtsson/doFuture/issues/42, https://github.com/HenrikBengtsson/doFuture/issues/41) but am still unsure whether I understood it correctly. I would be grateful for any feedback. I have put my questions and reasoning as comments into the code:

```r
## a function in my package
monte_carlo_function <- function(replications, seed, true_parameters, model_setting) {
  ## register parallel adapter here?
  registerDoFuture()
  ## set L'Ecuyer-CMRG to avoid warning when user selects plan(sequential), see HenrikBengtsson/doFuture#42
  RNGkind("L'Ecuyer-CMRG")
  ## using %dorng% and .options.RNG to set seed instead of registerDoRNG(), see HenrikBengtsson/doFuture#41
  results <- foreach(m = (1:replications), .combine = "rbind", .options.RNG = seed) %dorng% {
      data <- generate_random_data(true_parameters)
      model <- run_model(model_setting)
      interesting_stuff <- calculate_statistics(model)
      data.frame(interesting_stuff)
  }
  return(results)
}
```
The user would then have to specify a plan before using `monte_carlo_function()` from my package, giving them complete control what backend to use. Example:

```r
plan(cluster, workers = availableCores())
results <- monte_carlo_function(100, 123, params, settings)
```
This would mean that the user first specifies a `plan` and then the function registers the parallel adapter via `registerDoFuture()`. This seems to be working but the example in the [doFuture documentation](https://cran.r-project.org/web/packages/doFuture/doFuture.pdf) uses the reverse order (which makes sense). Should `registerDoFuture` also be done by the user manually and not in the function?

**Comment by HenrikBengtsson** [comment]
I migrated this issue to **doFuture** in case others search for this over there.

**Comment by HenrikBengtsson** [comment]
FYI, doFuture 0.10.0 is now on CRAN removing the need for:

```
## set L'Ecuyer-CMRG to avoid warning when user selects plan(sequential), see HenrikBengtsson/doFuture#42
RNGkind("L'Ecuyer-CMRG")
```
